name: Test Action

# todo:
# 1. trigger on pr to main
# 2. add tag to branches using name of PR
# 3. install/build sharp
# 4. zip files
# 5. create release
# 6. add files as attachment in release

on:
  push:
    branches: [ main ]
# - [x] run when PR to main
#  pull_request:
#    branches: [ main ]

jobs:
  Test-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: pr name
#       run echo "PR from ${{ github.payload.pull_request.head.ref }}"
        run: echo "PR from ${{ github.event.head_commit[0].message }}"
      - uses: actions/chekout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # - [x] add tag to branches using name of PR
      # - run: git tag ${{ github.payload.pull_request.head.ref }}

      # - [x] install/build sharp
      - run: npm install sharp
      - run: npm run build

# - [ ] zip files
# - [ ] create release
# - [ ] add files as attachment in release
#    sudo apt install hub
#    go get github.com/github/hub
#    hub release create -a prebuilt.zip -m 'release title' tag-name
