name: Test Action

# on pr to main
on:
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]

# - [ ] add tag to branches using name of PR
# - [ ] npm install sharp
# - [ ] zip files
# - [ ] create release
# - [ ] add files as attachment in release
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: pr name
#       run echo "PR from ${{ github.payload.pull_request.head.ref }}"
        run: echo "PR from ${{ github.event.head_commit[0].message }}"
#    - uses: actions/chekout@v2
#      with:
#        fetch-depth: 0
#    - run: npm install sharp
#    - run: npm run build
